In [1]:
import os
os.listdir()

['.ipynb_checkpoints',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'supermarkets.zip',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb']

In [2]:
import pandas
pandas.read_excel("supermarkets.xlsx")

,ID,Address,City,State,Country,Supermarket Name,Number of Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [3]:
pandas.read_csv("supermarkets-commas.txt")

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [4]:
pandas.read_csv("supermarkets-semi-colons.txt", sep=";")

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [5]:
os.listdir()

['.ipynb_checkpoints',
 'data.txt',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'supermarkets.zip',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb']

In [6]:
pandas.read_csv("data.txt")

   1.3   1.5
0  2.3   2.7
1  1.3   1.5
2  2.3   2.7
3  1.3   1.5
4  2.3   2.7

In [7]:
pandas.read_csv("data.csv", Header=None)

TypeError: read_csv() got an unexpected keyword argument 'Header'

In [8]:
pandas.read_csv("data.csv", header=None)

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [9]:
pandas.read_csv("data.csv", header = None)

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [10]:
pandas.read_csv("data.txt", header = None)

     0    1
0  1.3  1.5
1  2.3  2.7
2  1.3  1.5
3  2.3  2.7
4  1.3  1.5
5  2.3  2.7

In [12]:
df = pandas.read_csv("data.txt", header = None)
df.columns = ["Mon","Tue"]
df

   Mon  Tue
0  1.3  1.5
1  2.3  2.7
2  1.3  1.5
3  2.3  2.7
4  1.3  1.5
5  2.3  2.7